name: CustomGod
main: me.vaape.customgod.CustomGod
version: 1.0
api-version: 1.18
depend: [ArmorEquipEvent, WorldGuard]
commands:
  givegod:
    description: Gives god items
    permission: customgod.givegod
  givesnowy:
    description: Gives snowy items
    permission: customgod.givesnowy
  giveval:
    description: Gives val items
    permission: customgod.giveval
  giveeaster:
    description: Gives val items
    permission: customgod.giveeaster